
filetype = '.csv'
logging_level = 'ERROR'
data_folder = 'Data'
hist_folder = 'Historical'
financial_folder = 'Financial'
prtf_folder = 'Portfolios'
as_folder = 'Asset_Selection'
po_folder = 'Portfolio_Optimization'
assets_folder = 'Assets'
