# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 750)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabAll = QtWidgets.QTabWidget(self.centralwidget)
        self.tabAll.setObjectName("tabAll")
        self.tabAssetSel = QtWidgets.QWidget()
        self.tabAssetSel.setObjectName("tabAssetSel")
        self.tabAll.addTab(self.tabAssetSel, "")
        self.tabPortOpt = QtWidgets.QWidget()
        self.tabPortOpt.setObjectName("tabPortOpt")
        self.tabAll.addTab(self.tabPortOpt, "")
        self.verticalLayout.addWidget(self.tabAll)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabAll.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabAll.setTabText(self.tabAll.indexOf(self.tabAssetSel), _translate("MainWindow", "Asset Selection"))
        self.tabAll.setTabText(self.tabAll.indexOf(self.tabPortOpt), _translate("MainWindow", "Portfolio Optimization"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
